name: Mark stale issues and pull requests

on:
  workflow_run:
    workflows: ["Scala CI"]
    branches: [workflow-dependancy]
    types:
      - completed

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Print hello
        run: echo "hello sakshi"